//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopMetals.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sale()
        {
            this.SaleInfoes = new HashSet<SaleInfo>();
        }
    
        public int ID { get; set; }
        public int IDCustomer { get; set; }
        public Nullable<int> CodeSeller { get; set; }
        public Nullable<int> IDStatus { get; set; }
        public System.DateTime Date { get; set; }
        public virtual Customer Customer { get; set; }
        public string AllItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleInfo> SaleInfoes { get; set; }
        public virtual Status Status { get; set; }
        public virtual Seller Seller { get; set; }
    }
}
