//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopMetals.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleInfo
    {
        public int IDSales { get; set; }
        public int IDItem { get; set; }
        public int Count { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Sale Sale { get; set; }
    }
}
